-- Migración: tabla page_views (tracking de visitas) + función helper para
-- contar usuarios totales desde el panel admin. Ejecutar en Supabase SQL Editor.
--
-- Modelo:
-- - Append-only, sin FK a usuario. Solo contamos hits, no identificamos.
-- - INSERT abierto a anon + authenticated (la home la llama con la anon key).
-- - SELECT cerrado: sin policy → solo service_role lee. El conteo se hace
--   en /api/admin/metricas con el cliente service_role.

CREATE TABLE IF NOT EXISTS page_views (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  path        TEXT
);

COMMENT ON TABLE  page_views      IS 'Hits de visita a páginas públicas. Append-only, sin asociación a usuario.';
COMMENT ON COLUMN page_views.path IS 'Pathname del cliente al momento de la visita (ej. /, /categorias/electronicos). Nullable.';

-- Índice para breakdowns por rango temporal en el futuro.
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views(created_at DESC);

ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;

-- INSERT abierto. Sin policy de SELECT/UPDATE/DELETE → lectura solo via service_role.
-- Patrón DROP+CREATE para que el script sea re-ejecutable sin error:
-- Postgres NO soporta `IF NOT EXISTS` en `CREATE POLICY`.
DROP POLICY IF EXISTS "page_views_insert_anon" ON page_views;
CREATE POLICY "page_views_insert_anon"
  ON page_views FOR INSERT TO anon, authenticated WITH CHECK (true);

-- ─────────────────────────────────────────────────────────────────────────
-- Función helper para contar auth.users.
--
-- PostgREST por default no expone el schema `auth`, así que ni siquiera con
-- service_role se puede hacer `from('auth.users')` vía REST. La forma limpia
-- es exponer un wrapper SECURITY DEFINER en public y restringir EXECUTE
-- solo a service_role.
CREATE OR REPLACE FUNCTION public.count_auth_users()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT COUNT(*)::BIGINT FROM auth.users;
$$;

REVOKE EXECUTE ON FUNCTION public.count_auth_users() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.count_auth_users() FROM anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.count_auth_users() TO service_role;
