ALTER TABLE pedidos
  ADD COLUMN IF NOT EXISTS escrow_liberado   BOOLEAN       NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS igv               NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arancel           NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pais_comprador    TEXT          NOT NULL DEFAULT 'PE',
  ADD COLUMN IF NOT EXISTS nombre_comprador  TEXT          NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email_comprador   TEXT          NOT NULL DEFAULT '';
